site_name: Health Mod
site_url: https://healthstore.github.io/android_vendor_lineage_health
repo_name: healthstore/android_vendor_lineage_health
site_description: "Health Mod"
site_author: The LineageOS Project
copyright: 'Copyright &copy; 2020-2021 The LineageOS Project'
remote_branch: gh-pages

theme:
  name: 'material'
  # favicon: img/favicon.ico
  # logo: img/logo.png
  palette:
    primary: 'white'
    accent: 'deep orange'

extra_css:
  - 'css/app.css'

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - tables

nav:
  - 'Overview': index.md
  - 'Components': components.md
  - 'Metrics': metrics.md
  - 'Partner': partner.md
  - 'Info': product_document.md
  - 'JavaDoc': javadocs/index.html